"""knowledge graph nodes and edges

Revision ID: 7aad5a7b7385
Revises: 0d1e77bfc695
Create Date: 2026-07-16 02:26:49.199629

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7aad5a7b7385"
down_revision: Union[str, None] = "0d1e77bfc695"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kg_nodes",
        sa.Column("node_id", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("node_id", name=op.f("pk_kg_nodes")),
    )
    op.create_index(op.f("ix_kg_nodes_created_at"), "kg_nodes", ["created_at"], unique=False)
    op.create_index(op.f("ix_kg_nodes_type"), "kg_nodes", ["type"], unique=False)
    op.create_table(
        "kg_edges",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=200), nullable=False),
        sa.Column("target_id", sa.String(length=200), nullable=False),
        sa.Column("relation", sa.String(length=32), nullable=False),
        sa.Column("provenance", sa.String(length=512), nullable=False),
        sa.Column("created_version", sa.Integer(), nullable=False),
        sa.Column("removed_version", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"], ["kg_nodes.node_id"], name=op.f("fk_kg_edges_source_id_kg_nodes")
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["kg_nodes.node_id"], name=op.f("fk_kg_edges_target_id_kg_nodes")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kg_edges")),
    )
    op.create_index(
        op.f("ix_kg_edges_created_version"), "kg_edges", ["created_version"], unique=False
    )
    op.create_index(
        op.f("ix_kg_edges_removed_version"), "kg_edges", ["removed_version"], unique=False
    )
    op.create_index(op.f("ix_kg_edges_source_id"), "kg_edges", ["source_id"], unique=False)
    op.create_index(op.f("ix_kg_edges_target_id"), "kg_edges", ["target_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kg_edges_target_id"), table_name="kg_edges")
    op.drop_index(op.f("ix_kg_edges_source_id"), table_name="kg_edges")
    op.drop_index(op.f("ix_kg_edges_removed_version"), table_name="kg_edges")
    op.drop_index(op.f("ix_kg_edges_created_version"), table_name="kg_edges")
    op.drop_table("kg_edges")
    op.drop_index(op.f("ix_kg_nodes_type"), table_name="kg_nodes")
    op.drop_index(op.f("ix_kg_nodes_created_at"), table_name="kg_nodes")
    op.drop_table("kg_nodes")
    # ### end Alembic commands ###
