"""journal entries

Revision ID: 7e63fea92f78
Revises: b5c6d7e8f9a0
Create Date: 2026-07-16 04:24:37.711762

"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7e63fea92f78"
down_revision: Union[str, None] = "b5c6d7e8f9a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("original_hypothesis", sa.Text(), nullable=False),
        sa.Column(
            "supporting_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "counter_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("expected_outcome", sa.Text(), nullable=False),
        sa.Column("actual_outcome", sa.Text(), nullable=False),
        sa.Column("lessons_learned", sa.Text(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_journal_entries")),
    )
    op.create_index(
        op.f("ix_journal_entries_decision_id"), "journal_entries", ["decision_id"], unique=False
    )
    op.create_index(
        op.f("ix_journal_entries_recorded_at"), "journal_entries", ["recorded_at"], unique=False
    )
    with op.batch_alter_table("evidence") as batch_op:
        batch_op.alter_column("metadata_json", existing_type=sa.JSON(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence") as batch_op:
        batch_op.alter_column("metadata_json", existing_type=sa.JSON(), nullable=True)
    op.drop_index(op.f("ix_journal_entries_recorded_at"), table_name="journal_entries")
    op.drop_index(op.f("ix_journal_entries_decision_id"), table_name="journal_entries")
    op.drop_table("journal_entries")
    # ### end Alembic commands ###
